### sub
GET http://localhost:8765/catmq/sub?t=com.abysscat.catmq.test&cid=123

### send
POST http://localhost:8765/catmq/send?t=com.abysscat.catmq.test&cid=123
Content-Type: application/json

{
  "body" : "{\"id\":566,\"item\":\"item3\",\"price\":3.0}"
}

### recv
GET http://localhost:8765/catmq/recv?t=com.abysscat.catmq.test&cid=123

### ack
GET http://localhost:8765/catmq/ack?t=com.abysscat.catmq.test&cid=123&offset=822

### stat
GET http://localhost:8765/catmq/stat?t=com.abysscat.catmq.test&cid=123