### sub
GET http://localhost:8765/catmq/sub?t=a&cid=123

### send
POST http://localhost:8765/catmq/send?t=a&cid=123
Content-Type: application/json

{
  "body" : "{\"id\":5,\"item\":\"item3\",\"price\":3.0}"
}

### recv
GET http://localhost:8765/catmq/recv?t=a&cid=123

### ack
GET http://localhost:8765/catmq/ack?t=a&cid=123&offset=1